### ISSUE TITLE
hostnames from /etc/hosts seems to not be honored

### ISSUE THREAD

**Issue by martinqvistgard** [quangson91/intellij_rest_cli#8]
It seems that hostnames from /etc/hosts is not honored by rest-cli.

This can be a problem in environments with docker and especially in more complex ci setups where docker in docker is used.

With this test script:

```js
// POST http://127.0.0.1:8081/en/api/auth/login
POST http://docker.local:8081/en/api/auth/login
Content-Type: application/json;charset=UTF-8
Accept: application/json

{"username":"xxxx","password":"qwerty"}

> {%
client.test("That request was successful", function() {
    client.assert(response.status === 200, "Response status is not 200");
});
```

And this line in my /etc/hosts file
`127.0.0.1       docker.local`

I get this result from php storm
![image](https://user-images.githubusercontent.com/703595/89381502-900a0d00-d6f9-11ea-8f1c-3197b0d5d869.png)

With rest-cli this is what I get:
```
Environment name: null; Script: /home/martin//test/HTTP/WorkflowTest.http
__________________________________________________

##### Execute request http://docker.local:8081/en/api/auth/login #####
Can't execute request target: http://docker.local:8081/en/api/auth/login
java.lang.UnsupportedOperationException: Can't execute request target: http://docker.local:8081/en/api/auth/login                                             
        at uos.dev.restcli.executor.OkhttpRequestExecutor.execute(OkhttpRequestExecutor.kt:35)                                                                              
        at uos.dev.restcli.RestCli$call$$inlined$forEach$lambda$1.invoke(RestCli.kt:79)
        at uos.dev.restcli.RestCli$call$$inlined$forEach$lambda$1.invoke(RestCli.kt:26)
        at uos.dev.restcli.RestCli.runSafe(RestCli.kt:130)
        at uos.dev.restcli.RestCli.call(RestCli.kt:74)
        at uos.dev.restcli.RestCli.call(RestCli.kt:26)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1853)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
        at picocli.CommandLine.execute(CommandLine.java:1978)
        at uos.dev.restcli.AppKt.main(App.kt:7)


```

**Comment by quangson91** [comment]
Great catch again!
I will check and fix it soon. 
Thanks!

**Comment by martinqvistgard** [comment]
My colleague pointed out that I had made i mistake when pasting the example script, It should of course be docker.local and not 127.0.0.1

**Comment by quangson91** [comment]
Yup.
It should be
```
// POST http://docker.local:8081/en/api/auth/login
POST http://docker.local:8081/en/api/auth/login
Content-Type: application/json;charset=UTF-8
Accept: application/json

{"username":"xxxx","password":"qwerty"}

> {%
client.test("That request was successful", function() {
    client.assert(response.status === 200, "Response status is not 200");
});
```
Is that right?

**Comment by martinqvistgard** [comment]
Exactly!

**Comment by quangson91** [comment]
@martinqvistgard I fixed this issue in the new release version: https://github.com/quangson91/intellij_rest_cli/releases/tag/v1.3

Please take a look :) 

Thank you!

**Comment by martinqvistgard** [comment]
Tested and verified that it now works!
 
Thanks, again :)
